/* global module, require, Buffer */
const crypto = require('crypto');
const fs = require('fs');
const STATES = ['offered', 'accepted', 'transferring', 'paused', 'verifying', 'completed', 'cancelled', 'failed'];
const CHUNK_SIZE = 5 * 1024 * 1024;
function createManifest({ transferId = `transfer_${crypto.randomBytes(12).toString('hex')}`, senderId, receiverId, name, size, sha256, chunkSize = CHUNK_SIZE } = {}) { if (!senderId || !receiverId || !name || !Number.isSafeInteger(size) || size < 0 || !/^[a-f0-9]{64}$/i.test(sha256 || '')) throw new Error('传输清单参数无效'); return { protocol: 'innernet-transfer', protocolVersion: 1, transferId, senderId, receiverId, name: String(name).replace(/[\\/:*?"<>|]/g, '_').slice(0, 180), size, sha256: sha256.toLowerCase(), chunkSize, chunkCount: Math.ceil(size / chunkSize), createdAt: Date.now() }; }
function createTransferState(manifest) { return { manifest, state: 'offered', received: new Set() }; }
function acceptTransfer(state, receiverId) { if (state.manifest.receiverId !== receiverId || state.state !== 'offered') throw new Error('传输接收方或状态无效'); return { ...state, state: 'accepted' }; }
function markChunk(state, index) { if (!Number.isInteger(index) || index < 0 || index >= state.manifest.chunkCount) throw new Error('分块序号无效'); state.received.add(index); return state; }
function missingChunks(state) { const missing = []; for (let i = 0; i < state.manifest.chunkCount; i++) if (!state.received.has(i)) missing.push(i); return missing; }
function createTransferAuthorization(manifest, pairingAuthorization, now = Date.now()) { if (!manifest?.transferId || !pairingAuthorization?.authorizationId || !pairingAuthorization.deviceId) throw new Error('传输授权参数无效'); return { transferAuthorizationId: `ta_${crypto.randomBytes(16).toString('hex')}`, authorizationId: pairingAuthorization.authorizationId, transferId: manifest.transferId, deviceId: pairingAuthorization.deviceId, issuedAt: now, expiresAt: Math.min(pairingAuthorization.expiresAt || now, now + 10 * 60 * 1000) }; }
function protectTransferAuthorization(authorization, pairingCode) { if (!authorization || !/^\d{6}$/.test(String(pairingCode || ''))) throw new Error('传输授权保护参数无效'); const key = crypto.createHash('sha256').update(`innernet-pairing:${pairingCode}`).digest(); const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', key, iv); const value = Buffer.concat([cipher.update(JSON.stringify(authorization), 'utf8'), cipher.final()]); return { iv: iv.toString('base64'), tag: cipher.getAuthTag().toString('base64'), value: value.toString('base64') }; }
function unprotectTransferAuthorization(protectedValue, pairingCode) { if (!protectedValue?.iv || !protectedValue?.tag || !protectedValue?.value || !/^\d{6}$/.test(String(pairingCode || ''))) throw new Error('传输授权解密参数无效'); const key = crypto.createHash('sha256').update(`innernet-pairing:${pairingCode}`).digest(); const decipher = crypto.createDecipheriv('aes-256-gcm', key, Buffer.from(protectedValue.iv, 'base64')); decipher.setAuthTag(Buffer.from(protectedValue.tag, 'base64')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(protectedValue.value, 'base64')), decipher.final()]).toString('utf8')); }
function createTransferChallenge({ transferId, senderId, receiverId, now = Date.now(), ttlMs = 2 * 60 * 1000 } = {}) { if (!/^transfer_[a-f0-9]{24}$/.test(String(transferId || '')) || !senderId || !receiverId) throw new Error('传输挑战参数无效'); return { protocol: 'innernet-transfer-challenge', version: 1, challengeId: `ch_${crypto.randomBytes(16).toString('hex')}`, transferId, senderId, receiverId, nonce: crypto.randomBytes(32).toString('base64url'), issuedAt: now, expiresAt: now + ttlMs }; }
function signTransferChallenge(challenge, privateKey) { if (!challenge?.challengeId || !privateKey) throw new Error('签名参数无效'); return { challenge, signature: crypto.sign(null, Buffer.from(JSON.stringify(challenge)), privateKey).toString('base64') }; }
function verifyTransferChallenge(signed, publicKey, expected = {}, now = Date.now()) { const c = signed?.challenge; if (!c || c.expiresAt <= now || c.senderId !== expected.senderId || c.receiverId !== expected.receiverId || c.transferId !== expected.transferId) return false; return crypto.verify(null, Buffer.from(JSON.stringify(c)), publicKey, Buffer.from(String(signed.signature || ''), 'base64')); }
function authorizeTransfer(manifest, authorization, deviceId, now = Date.now()) { return Boolean(authorization && authorization.deviceId === deviceId && authorization.transferId === manifest?.transferId && authorization.authorizationId && authorization.transferAuthorizationId && authorization.expiresAt > now && manifest.senderId && manifest.receiverId); }
function transition(state, next) { if (!STATES.includes(next)) throw new Error('传输状态无效'); const allowed = { offered: ['accepted', 'cancelled'], accepted: ['transferring', 'cancelled'], transferring: ['paused', 'verifying', 'cancelled', 'failed'], paused: ['transferring', 'cancelled'], verifying: ['completed', 'failed'] }; if (!allowed[state.state]?.includes(next)) throw new Error('不允许的传输状态转换'); return { ...state, state: next }; }
function hashFile(file) { return new Promise((resolve, reject) => { const hash = crypto.createHash('sha256'); const input = fs.createReadStream(file); input.on('data', (chunk) => hash.update(chunk)); input.on('error', reject); input.on('end', () => resolve(hash.digest('hex'))); }); }
async function finalizeFile(state, tempFile, targetFile) { if (state.state !== 'verifying') throw new Error('传输尚未进入校验阶段'); const digest = await hashFile(tempFile); if (digest !== state.manifest.sha256) throw new Error('文件校验失败'); fs.mkdirSync(require('path').dirname(targetFile), { recursive: true }); fs.renameSync(tempFile, targetFile); return transition(state, 'completed'); }
module.exports = { STATES, CHUNK_SIZE, createTransferChallenge, signTransferChallenge, verifyTransferChallenge, protectTransferAuthorization, unprotectTransferAuthorization, createManifest, createTransferState, acceptTransfer, markChunk, missingChunks, createTransferAuthorization, authorizeTransfer, transition, hashFile, finalizeFile };
