/* global setInterval, clearInterval */
import React, { useEffect, useState } from 'react';
const statusText = (d) => d.trust?.state === 'identity_changed' ? '设备身份已变化' : d.presence?.online ? (d.trust?.state === 'trusted' ? '在线 · 已信任' : '在线 · 待配对') : '离线';

export default function DeviceCenter() {
  const [devices, setDevices] = useState([]); const [localDeviceId, setLocalDeviceId] = useState(''); const [pairing, setPairing] = useState(null); const [incoming, setIncoming] = useState([]); const [codes, setCodes] = useState({}); const [notice, setNotice] = useState('');
  const refresh = () => { Promise.all([window.api.device?.info?.(), window.api.discovery?.list?.()]).then(([local, all]) => { if (local?.deviceId) { setLocalDeviceId(local.deviceId); setDevices([{ ...local, presence: { ...(local.presence || {}), online: true }, network: { ...(local.network || {}), preferredAddress: '本机' }, trust: { ...(local.trust || {}), state: 'trusted' } }, ...(all || []).filter((d) => d.deviceId !== local.deviceId)]); } else setDevices(all || []); }).catch(() => {}); window.api.pairing?.pending?.().then(setIncoming).catch(() => {}); };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 5000); const off = window.api.pairing?.onIncoming?.((item) => setIncoming((all) => all.some((x) => x.sessionId === item.sessionId) ? all : [...all, item])); return () => { clearInterval(timer); off?.(); }; }, []);
  const requestPairing = async (device) => {
    const result = await window.api.pairing.request(device);
    if (result.ok) { setPairing({ ...result, deviceName: device.deviceName, remoteDeviceId: device.deviceId, state: 'pending' }); setNotice('配对请求已送达对端，请核对两台设备显示的 6 位验证码。'); }
    else setNotice(result.reasonCode === 'REMOTE_UNREACHABLE' ? '目标设备暂时无法连接，请确认它已开机且配对服务可访问。' : '无法发起配对，请检查目标设备信息后重试。');
  };

  useEffect(() => {
    if (!pairing?.sessionId || pairing.state !== 'pending') return undefined;
    const poll = async () => { const result = await window.api.pairing.status(pairing); if (result.ok && result.state !== 'pending') { setPairing((old) => ({ ...old, state: result.state })); setNotice(result.state === 'accepted' ? '对端已确认验证码，配对完成。' : '配对未完成，请重新发起。'); } };
    poll(); const timer = setInterval(poll, 2000); return () => clearInterval(timer);
  }, [pairing?.sessionId, pairing?.state, pairing?.host, pairing?.port]);
  const confirmIncoming = async (item) => { const result = await window.api.pairing.confirmIncoming({ sessionId: item.sessionId, code: codes[item.sessionId] || '' }); if (result.ok) { setIncoming((all) => all.filter((x) => x.sessionId !== item.sessionId)); setNotice(`已确认 ${item.fromDeviceName} 的配对请求。`); } else setNotice(`验证码未通过：${result.reasonCode || 'UNKNOWN'}`); };
  return <section className="device-center"><div className="device-center-head"><div><h2>设备中心</h2><p>查看本机与已发现的 InnerNet 设备；敏感操作需先完成配对。</p></div><button className="btn" onClick={refresh}>重新发现</button></div>{incoming.map((item) => <div className="pairing-notice" key={item.sessionId}><strong>{item.fromDeviceName}</strong> 请求与本机配对。请确认两端显示的配对码一致：<strong>{item.code}</strong><input aria-label="配对验证码" value={codes[item.sessionId] || ''} maxLength="6" onChange={(e) => setCodes({ ...codes, [item.sessionId]: e.target.value.replace(/\D/g, '') })} /><button className="btn small" onClick={() => confirmIncoming(item)}>允许配对</button><button className="btn small" onClick={async () => { await window.api.pairing.rejectIncoming({ sessionId: item.sessionId }); setIncoming((all) => all.filter((x) => x.sessionId !== item.sessionId)); }}>拒绝</button></div>)}<div className="device-grid">{devices.map((d) => <article className="device-card" key={d.deviceId}><div className="device-card-title"><span className="device-type-icon">{d.deviceType === 'laptop' ? '💻' : d.platform === 'win32' ? '🖥️' : '▣'}</span><div><h3>{d.deviceName}</h3><small>{d.hostname || d.platform}</small></div></div><div className={`device-state ${d.presence?.online ? 'online' : 'offline'}`}>{statusText(d)}</div><dl><dt>地址</dt><dd>{d.network?.preferredAddress || '本机'}</dd><dt>设备 ID</dt><dd className="mono">{d.deviceId}</dd></dl><div className="device-capabilities">{Object.entries(d.capabilities || {}).filter(([, c]) => c.supported).map(([name, c]) => <span key={name} className={c.available ? 'cap-on' : 'cap-off'}>{name}{c.available ? ' 可用' : ' 未就绪'}</span>)}</div>{d.deviceId !== localDeviceId && d.trust?.state !== 'trusted' && d.trust?.state !== 'identity_changed' && <button className="btn small" onClick={() => requestPairing(d)}>发起配对</button>}{d.trust?.state === 'trusted' && <button className="btn small" onClick={async () => { await window.api.pairing.unpair({ deviceId: d.deviceId }); setNotice(`已解除与 ${d.deviceName} 的配对。`); refresh(); }}>解除配对</button>}{d.trust?.state === 'identity_changed' && <span className="cap-off">为保护数据安全，请先解除配对后重新配对</span>}</article>)}</div>{pairing && <div className="pairing-notice">{pairing.state === 'pending' ? <>请在 <strong>{pairing.deviceName}</strong> 输入一次性配对码 <strong>{pairing.code}</strong>（5 分钟内有效）</> : <strong>{pairing.state === 'accepted' ? '配对成功' : `配对状态：${pairing.state}`}</strong>}<button className="btn small" onClick={() => setPairing(null)}>关闭</button></div>}{notice && <div className="chat-empty">{notice}</div>}{!devices.length && <div className="chat-empty">正在加载设备信息…</div>}</section>;
}
