import React, { useEffect, useState } from 'react';
const LABELS = { discovery: '设备发现（UDP）', chat: '群聊（TCP）', pairing: '安全配对（TCP）', transfer: '原生传输（TCP）' };
export default function ServiceSettings() {
  const [ports, setPorts] = useState(null); const [health, setHealth] = useState(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const scan = () => window.api.services?.health?.().then(setHealth).catch(() => setMessage('健康检查失败，请重试。'));
  useEffect(() => { const defaults = { discovery: 49321, chat: 7890, pairing: 7891, transfer: 49152 }; const load = window.api.services?.ports?.(); if (!load) { setPorts(defaults); setMessage('当前运行版本未提供端口配置 IPC，已显示默认端口；请重启开发服务。'); } else load.then(setPorts).catch(() => { setPorts(defaults); setMessage('端口配置读取失败，已显示默认端口。'); }); scan(); }, []);
  const save = async () => { if (!window.api.services?.setPorts) { setMessage('当前运行版本不支持保存端口配置，请重启开发服务。'); return; } setBusy(true); const result = await window.api.services.setPorts(ports); setBusy(false); setMessage(result.ok ? '端口配置已保存，请重启应用后生效。' : '端口配置保存失败。'); scan(); };
  if (!ports) return <section className="settings"><p>正在读取服务配置…</p></section>;
  return <section className="settings service-settings"><div className="device-center-head"><div><h2>服务设置</h2><p>统一管理服务健康状态和端口。扫描只检查本机，不扫描其他设备。</p></div><button className="btn" onClick={scan}>重新检查</button></div>{health && <><h3>健康检查</h3><div className="service-health-list">{health.services.map((item) => <div key={item.name}><strong>{LABELS[item.name] || item.name}</strong><span>:{item.port}</span><em className={item.state === 'healthy' ? 'cap-on' : 'cap-off'}>{item.state === 'healthy' ? '运行正常' : item.state === 'occupied' ? `端口被占用${item.suggestedPort ? `，建议改用 ${item.suggestedPort}` : ''}` : '端口空闲'}</em>{item.state === 'occupied' && item.suggestedPort && <button className="btn small" onClick={() => setPorts({ ...ports, [item.name]: item.suggestedPort })}>使用建议端口</button>}</div>)}</div></>}<h3>当前端口信息</h3><div className="service-port-grid service-port-readonly">{Object.entries(ports).map(([name, value]) => <div key={name}><span>{LABELS[name]}</span><strong>:{value}</strong></div>)}</div><h3>端口配置 <span className="settings-hint">保存后需重启应用生效</span></h3><div className="service-port-grid">{Object.entries(ports).map(([name, value]) => <label key={name}>{LABELS[name]}<input type="number" min="1" max="65535" value={value} onChange={(e) => setPorts({ ...ports, [name]: e.target.value })} /></label>)}</div><button className="btn primary" disabled={busy} onClick={save}>{busy ? '保存中…' : '保存端口配置'}</button>{message && <p className="settings-hint">{message}</p>}</section>;
}
